### ISSUE TITLE
onUp() sometimes are not being triggered

### ISSUE THREAD

**Issue by ponnex** [justasm/Bugstick#8]
onUp() sometimes are not being triggered. If this is beyond what the library can do at least onDrag should be giving 0 offset for us to identify if the stick is at the center. Reason? I need to have a command that send of "stop" but the only way to do it using bugstick is through onUp, so giving the ability to give 0 offset would be great :D

**Comment by justasm** [comment]
This is not beyond what the library should be able to do 😄 

Could you please clarify in what situations you notice that onUp() is not being called? Can you reliably reproduce it, and if so, share a series of steps? Do you use the `lock()` feature of Bugstick?

**Comment by ponnex** [comment]
False alarm! xD I just made series of experiment as well as confirmation to this issue. onUp() actually working fine the issue is on another mater. Please closed this issue and sorry for the inconvenience. Great library! I might be adding another issue for possible enhancements as well thanks again!

**Comment by ponnex** [comment]
False alarm! xD I just made series of experiment as well as confirmation to this issue. onUp() actually working fine the issue is on another mater. Sorry for the inconvenience. Great library though! might be adding another issue for possible enhancements as well thanks again!
